### ISSUE TITLE
Ball momentum stays constant

### ISSUE THREAD

**Issue by dragonash2019** [Xiexe/VRCBilliards#6]
There seem to be random times when the ball momentum stays at a constant until it hits a rail, even when it's a soft hit. Doesn't happen often, but when it does, it's really obvious.

Thanks for taking up the project!

**Comment by Terri00** [comment]
What you are observing is when the ball is in 'rolling' motion.

When a ball is rolling on a pool table it experiences very little friction. ( Typical friction coefficient between ball-cloth has been measured to be in the range 0.005µ – 0.015µ )

When applied over a timestep of 0.0125s, in earth gravity, with a pool ball weighing 160 grams, it decelerates by 0.0012258 m/s.

The ball can _never_ have a constant velocity because of this.

**Comment by dragonash2019** [comment]
Fair enough. It feels different when observing from the human aspect (eyes). Looking at a few youtube videos, I guess it is pretty accurate. I'll close this out based on that. Thanks Harry.

**Comment by Terri00** [comment]
Ya I was surprised by it also when I implemented it (before there was no rolling in the engine, everything acted as if it diddn't rotate at all)

I had to take a look at some professional matches after, and see they roll the same so it made sense in the name of accuracy to keep it. As far as i'm aware I did not botch any of the physics calculations ^^
